# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f47f679cee8ff631c8386087662f0550"
name = "ip-216-app"
handle = "ip-216-app"
application_url = "https://lender-convention-mode-ml.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "checkout-ui-extensions-test-store.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_discounts,write_discounts_allocator_functions,write_products"

[auth]
redirect_urls = [
  "https://lender-convention-mode-ml.trycloudflare.com/auth/callback",
  "https://lender-convention-mode-ml.trycloudflare.com/auth/shopify/callback",
  "https://lender-convention-mode-ml.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"
  compliance_topics = [ "customers/data_request", "customers/redact", "shop/redact" ]

[pos]
embedded = false
